[package]
name = "rlsd"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
directories = "6.0.0"
once_cell = "1.21.3"
rand = "0.9.1"
ratatui = "0.29.0"
serde_json = "1.0.140"
systemstat = "0.2.4"
tokio = {version="1.46.1", features=["full"]}
